// Extra exports merged into the Claude Design bundle global (cfg.extraEntries).
// The lucide icons are the set the site itself imports (grep "lucide-react" in
// src/); `toast` is the imperative API behind the <Toaster /> component, and `useForm`
// is required to drive the <Form> components (the design agent can only import
// from the bundle global).
export {
  ArrowRight,
  Bot,
  Boxes,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleDashed,
  Code,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  FileText,
  Gamepad2,
  GitMerge,
  GraduationCap,
  Heart,
  Info,
  Lightbulb,
  Link2,
  Loader2,
  Mail,
  Menu,
  MessageSquareReply,
  MessagesSquare,
  Mic,
  Minus,
  Moon,
  MoreHorizontal,
  PenLine,
  Plus,
  Printer,
  Radio,
  ScanSearch,
  ScanText,
  ScrollText,
  Search,
  Send,
  Server,
  ShieldAlert,
  Sparkles,
  Sun,
  Tags,
  Target,
  Waypoints,
  Workflow,
  Wrench,
  X,
} from "lucide-react";
export { toast } from "sonner";
export { useForm } from "react-hook-form";
